### ISSUE TITLE
2to3 python 2 -> 3 upgrade

### ISSUE THREAD

**Issue by johndpope** [steveKapturowski/tensorflow-rl#22]
this codebase is  a fantastic repository for reinforcement learning + tensorflow. 
did you consider upgrading to python 3? 
you can actually do this by going to terminal and punching in
2to3 *.py -w & it will update to latest python.

Here's a branch that's running python 3.
https://github.com/sangjin-park/tensorflow-rl

**Comment by steveKapturowski** [comment]
Hi @johndpope, I think it would be ideal to ensure it works with either python 2 or 3. I've been focused on other things recently but I can probably do the necessary refactoring soon. Does 2to3 ensure backwards compatibility or would it potentially break for python 2?

**Comment by johndpope** [comment]
it wont provide backwards compatibility.
but now days with miniconda / 
it's pretty simple to create a python 3 environment self contained with tensorflow - python3.

Here's a sample gist
https://gist.github.com/johndpope/187b0dd996d16152ace2f842d43e3990

I think @sangjin-park has also added some nice extension with SkipCTS on this branch
https://github.com/sangjin-park/tensorflow-rl/tree/dep
