### ISSUE TITLE
Wrong check for 'reward_threshold' property in cem_actor_learner.py

### ISSUE THREAD

**Issue by captify-alapite** [steveKapturowski/tensorflow-rl#5]
In the `train` method of the `CEMLearner`, there's the following check on line 86-89:
```
if elite_mean_reward > self.emulator.env.spec.reward_threshold:
    consecutive_successes += 1
else:
    consecutive_successes = 0
```
Unfortunately, the `reward_threshold` often evaluates to `None` (e.g. with `Pendulum-v0`) and consequently the inequality check succeeds, leading to premature halting of the CEM training.

**Comment by steveKapturowski** [comment]
Fixed: de2e6b324ab3c8b6139f898cf0e40357541986ff
