### ISSUE TITLE
no 'target_network' for A3CLearner when testing

### ISSUE THREAD

**Issue by NoobFang** [steveKapturowski/tensorflow-rl#9]
When run the test funcion of A3C algorithm (using --test option), the error of "AttributeError: 'A3CLearner' object has no attribute 'target_network'" occurs. I have checked the code and found that the 'target_network'  is only available for value_based_actor_learner.
So, is this a bug or I make some mistake?

**Comment by steveKapturowski** [comment]
Fixed
